FROM resin/%%RESIN_MACHINE_NAME%%-node:6 as buildStep

WORKDIR /usr/src/app

COPY package.json .
RUN npm install --production

FROM resin/%%RESIN_MACHINE_NAME%%-node:6-slim

WORKDIR /usr/src/app

COPY --from=buildStep /usr/src/app/node_modules node_modules
COPY . ./

CMD node src/app.js
